spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mediplant?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      validation-query: select 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: smart-agriculture

server:
  port: 8085
  tomcat:
    threads:
      max: 200
      min-spare: 100